import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText, Scale, Shield, AlertCircle } from 'lucide-react';

const Terms = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-blue-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <Link to="/" className="inline-flex items-center text-purple-600 hover:text-purple-700 mb-4">
            <ArrowLeft className="h-5 w-5 mr-2" />
            Back to Home
          </Link>
          <div className="flex items-center space-x-3">
            <FileText className="h-8 w-8 text-purple-600" />
            <h1 className="text-3xl font-bold text-gray-900">Terms & Conditions</h1>
          </div>
          <p className="text-gray-600 mt-2">Last updated: December 11, 2024</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-xl shadow-lg p-8 space-y-8">
          
          {/* Electronic Record */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
              <Shield className="h-6 w-6 text-purple-600 mr-2" />
              Electronic Record
            </h2>
            <p className="text-gray-700 leading-relaxed">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </section>

          {/* Platform Information */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Platform Information</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name{' '}
              <a href="https://stucareambassador.com" className="text-purple-600 hover:underline">
                https://stucareambassador.com
              </a>{' '}
              ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
            </p>
            <p className="text-gray-700 leading-relaxed">
              The Platform is owned by <strong>STUCARE INNOVATION AND CREATION PRIVATE LIMITED</strong>, a company incorporated under the Companies Act, 1956 with its registered office at 4th FLOOR, 108, THE PLATINA TANVI COMPLEX, NEXT S V ROAD, PETROL PUMP, DAHISAR EAST, Mumbai, Maharashtra, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
            </p>
          </section>

          {/* Terms of Use Overview */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Terms of Use Overview</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction.
            </p>
            <p className="text-gray-700 leading-relaxed mb-4">
              By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services').
            </p>
            <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded">
              <div className="flex items-start">
                <AlertCircle className="h-5 w-5 text-amber-500 mt-0.5 mr-3 flex-shrink-0" />
                <p className="text-amber-800 text-sm">
                  These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                </p>
              </div>
            </div>
          </section>

          {/* 1. Agreement to Terms */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">1. Agreement to Terms</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              <strong>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</strong>
            </p>
            <p className="text-gray-700 leading-relaxed">
              The use of Platform and/or availing of our Services is subject to the following Terms of Use: To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
            </p>
          </section>

          {/* 2. Disclaimer of Warranties */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">2. Disclaimer of Warranties</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose.
            </p>
            <p className="text-gray-700 leading-relaxed">
              You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
            </p>
          </section>

          {/* 3. Use at Your Own Risk */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">3. Use at Your Own Risk</h2>
            <p className="text-gray-700 leading-relaxed">
              Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
            </p>
          </section>

          {/* 4. Intellectual Property Rights */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">4. Intellectual Property Rights</h2>
            <p className="text-gray-700 leading-relaxed">
              The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
            </p>
          </section>

          {/* 5. User Obligations */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">5. User Obligations</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              You agree to comply with the following obligations:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
              <li>Acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws</li>
              <li>Pay us the charges associated with availing the Services</li>
              <li>Not use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you</li>
              <li>Understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner</li>
            </ul>
          </section>

          {/* 6. Third Party Links */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">6. Third Party Links</h2>
            <p className="text-gray-700 leading-relaxed">
              You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.
            </p>
          </section>

          {/* 7. Indemnification */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">7. Indemnification</h2>
            <p className="text-gray-700 leading-relaxed">
              You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
            </p>
          </section>

          {/* 8. Force Majeure */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">8. Force Majeure</h2>
            <p className="text-gray-700 leading-relaxed">
              Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
            </p>
          </section>

          {/* 9. Governing Law */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3 flex items-center">
              <Scale className="h-5 w-5 text-purple-600 mr-2" />
              9. Governing Law and Jurisdiction
            </h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
            </p>
            <p className="text-gray-700 leading-relaxed">
              All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Mumbai and Maharashtra.
            </p>
          </section>

          {/* 10. Contact Us */}
          <section className="bg-purple-50 rounded-lg p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4">10. Contact Us</h2>
            <p className="text-gray-700 mb-4">
              All concerns or communications relating to these Terms must be communicated to us using the contact information provided below:
            </p>
            <div className="space-y-2 text-gray-700">
              <p className="font-semibold">Stucare Innovation and Creation Pvt. Ltd.</p>
              <p>📞 +91 8691909003</p>
              <p>✉️ support@stucares.com</p>
              <p>📱 @stucare.innovation</p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
};

export default Terms;
